export type ResourceCategory = 'Marketing' | 'Commercial' | 'RH & Ops' | 'Direction' | 'Copywriting' | 'SEO'
export type ResourceType = 'SKILL' | 'PROMPT' | 'GUIDE'

export interface Resource {
  id: string
  category: ResourceCategory
  type: ResourceType
  badge: string
  badgeColor: string
  title: string
  desc: string
  bullets: string[]
  tags: string[]
  file: string
}

export const CATEGORIES: ResourceCategory[] = [
  'Marketing',
  'Commercial',
  'RH & Ops',
  'Direction',
  'Copywriting',
  'SEO',
]

export const resources: Resource[] = [
  {
    id: 'marketing-ai-team',
    category: 'Marketing',
    type: 'SKILL',
    badge: 'LE PLUS T\u00c9L\u00c9CHARG\u00c9',
    badgeColor: 'bg-amber-500',
    title: "L'\u00e9quipe IA qui 10x ton marketing",
    desc: "5 agents sp\u00e9cialis\u00e9s qui automatisent ta strat\u00e9gie marketing de A \u00e0 Z. Ce qu\u2019une agence facture 2\u202f000\u202f\u20ac/mois.",
    bullets: [
      'Agent Copywriter \u2014 tous tes textes sur mesure',
      'Agent Strat\u00e8ge \u2014 plan contenu 90 jours',
      'Agent SEO \u2014 optimisation automatique',
      'Agent Email \u2014 s\u00e9quences de prospection',
      'Agent Analyste \u2014 analyse et recommandations',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 12p', 'Valeur : 1\u202f800\u202f\u20ac'],
    file: '/resources/marketing-ai-team.zip',
  },
  {
    id: 'sales-ai-team',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'LE PLUS RENTABLE',
    badgeColor: 'bg-emerald-500',
    title: "L'\u00e9quipe IA qui close \u00e0 ta place",
    desc: '5 agents pour tout ton cycle de vente : prospection, devis, objections, relances, onboarding client.',
    bullets: [
      'Agent Prospecteur \u2014 messages ultra-personnalis\u00e9s',
      'Agent Devis \u2014 propositions qui convertissent',
      'Agent Objections \u2014 les bons arguments, toujours',
      'Agent Relance \u2014 suivi sans \u00eatre relou',
      'Agent Onboarding \u2014 accueil et fid\u00e9lisation client',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 2\u202f200\u202f\u20ac'],
    file: '/resources/sales-ai-team.zip',
  },
  {
    id: 'ops-rh-ai-team',
    category: 'RH & Ops',
    type: 'SKILL',
    badge: 'LE PLUS CONCRET',
    badgeColor: 'bg-blue-500',
    title: "L'\u00e9quipe IA qui pilote tes ops",
    desc: "5 agents pour le quotidien op\u00e9rationnel que personne n\u2019aime faire mais qui co\u00fbte des heures chaque semaine.",
    bullets: [
      "Agent Planning \u2014 plannings d'\u00e9quipe en 2 minutes",
      'Agent CR R\u00e9union \u2014 notes -> compte-rendu pro',
      'Agent Recrutement \u2014 fiches poste + tri CVs',
      'Agent Process \u2014 documentation SOP compl\u00e8te',
      'Agent Reporting \u2014 synth\u00e8se comit\u00e9 de direction',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 14p', 'Valeur : 1\u202f500\u202f\u20ac'],
    file: '/resources/ops-rh-ai-team.zip',
  },
  {
    id: 'copywriter-pro',
    category: 'Copywriting',
    type: 'PROMPT',
    badge: 'EXPERT',
    badgeColor: 'bg-purple-500',
    title: "Le copywriter IA qui \u00e9crit comme les meilleurs",
    desc: "Un system prompt de copywriter expert qui applique les frameworks AIDA, PAS, Hormozi \u00e0 chaque texte que tu produis.",
    bullets: [
      'Hooks qui stoppent le scroll LinkedIn',
      'Emails de prospection qui g\u00e9n\u00e8rent des r\u00e9ponses',
      'Pages de vente structur\u00e9es et persuasives',
      'Adapt\u00e9 \u00e0 ta voix et ton secteur',
    ],
    tags: ['System Prompt GPT', 'Skill Claude', 'Valeur : 800\u202f\u20ac'],
    file: '/resources/copywriter-pro.zip',
  },
  {
    id: 'linkedin-content-machine',
    category: 'Marketing',
    type: 'SKILL',
    badge: 'VIRAL',
    badgeColor: 'bg-pink-500',
    title: 'La machine \u00e0 contenus LinkedIn',
    desc: "Un skill complet pour produire 30 posts LinkedIn par mois en 2h. Structure, hooks, calendrier \u00e9ditorial, tout inclus.",
    bullets: [
      'Structure valid\u00e9e des meilleurs posts B2B',
      "5 types de hooks qui g\u00e9n\u00e8rent de l\u2019engagement",
      "Calendrier \u00e9ditorial 4 semaines pr\u00eat \u00e0 l\u2019emploi",
      'Adaptation automatique \u00e0 ton secteur et ICP',
      'Recyclage de contenu existant en nouveaux posts',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 8p', 'Valeur : 1\u202f200\u202f\u20ac'],
    file: '/resources/linkedin-content-machine.zip',
  },
  {
    id: 'seo-content-optimizer',
    category: 'SEO',
    type: 'SKILL',
    badge: 'TECHNIQUE',
    badgeColor: 'bg-cyan-500',
    title: "L\u2019agent SEO qui optimise tout ton contenu",
    desc: "Analyse tes pages, g\u00e9n\u00e8re des articles optimis\u00e9s, construit ta strat\u00e9gie de mots-cl\u00e9s. R\u00e9sultats en semaines.",
    bullets: [
      "Audit SEO on-page de n\u2019importe quelle URL",
      "G\u00e9n\u00e9ration d\u2019articles 1500+ mots optimis\u00e9s",
      'Strat\u00e9gie de clusters de mots-cl\u00e9s par secteur',
      'Optimisation des balises meta automatique',
      'Analyse de la concurrence et opportunit\u00e9s',
    ],
    tags: ['Skill Claude .md', 'Guide technique 16p', 'Valeur : 2\u202f000\u202f\u20ac'],
    file: '/resources/seo-content-optimizer.zip',
  },
  {
    id: 'cold-email-machine',
    category: 'Commercial',
    type: 'PROMPT',
    badge: '\u00c9PROUV\u00c9',
    badgeColor: 'bg-orange-500',
    title: 'La machine \u00e0 cold emails qui convertit',
    desc: "Le prompt exact pour g\u00e9n\u00e9rer des s\u00e9quences de prospection personnalis\u00e9es avec un taux de r\u00e9ponse >15%.",
    bullets: [
      'S\u00e9quence 5 emails avec timing optimal',
      'Personnalisation automatique par secteur/ICP',
      'Objets A/B test\u00e9s par type de prospect',
      'Follow-ups qui ne sont pas relous',
      'Adaptable \u00e0 ton offre en 5 minutes',
    ],
    tags: ['System Prompt GPT', 'Skill Claude', 'Guide 6p', 'Valeur : 900\u202f\u20ac'],
    file: '/resources/cold-email-machine.zip',
  },
  {
    id: 'direction-ai-assistant',
    category: 'Direction',
    type: 'SKILL',
    badge: 'STRAT\u00c9GIQUE',
    badgeColor: 'bg-indigo-500',
    title: "L\u2019assistant IA de direction g\u00e9n\u00e9rale",
    desc: "Un agent qui pense comme un DAF/DG : analyse financi\u00e8re, prise de d\u00e9cision, synth\u00e8ses strat\u00e9giques.",
    bullets: [
      'Analyse et synth\u00e8se de donn\u00e9es financi\u00e8res',
      'Aide \u00e0 la d\u00e9cision avec matrice risques/opportunit\u00e9s',
      'R\u00e9daction de notes de direction et board decks',
      'Suivi des KPIs et alertes automatiques',
      'Simulation de sc\u00e9narios business',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 3\u202f000\u202f\u20ac'],
    file: '/resources/direction-ai-assistant.zip',
  },
  {
    id: 'client-success-agent',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'FID\u00c9LISATION',
    badgeColor: 'bg-teal-500',
    title: "L\u2019agent IA qui garde tes clients",
    desc: "Un skill complet pour onboarder, engager et faire monter en gamme chaque client automatiquement.",
    bullets: [
      'S\u00e9quence onboarding client sur-mesure',
      "D\u00e9tection des signaux d\u2019insatisfaction",
      "Propositions d\u2019upsell au bon moment",
      'Rapports de suivi client automatis\u00e9s',
      "Scripts d\u2019appels de bilan trimestriel",
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 8p', 'Valeur : 1\u202f400\u202f\u20ac'],
    file: '/resources/client-success-agent.zip',
  },
  {
    id: 'proposal-writer-pro',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'CONVERSION',
    badgeColor: 'bg-rose-500',
    title: "L\u2019agent qui r\u00e9dige tes propositions commerciales",
    desc: "G\u00e9n\u00e8re des devis et propositions commerciales professionnels qui signent \u2014 avec calcul ROI int\u00e9gr\u00e9.",
    bullets: [
      'Structure de proposition qui convertit \u00e0 60%+',
      'Calcul ROI automatique selon le profil client',
      '3 niveaux de pricing (Starter/Standard/Premium)',
      'Arguments personnalis\u00e9s par secteur',
      'R\u00e9ponses aux objections pr\u00e9par\u00e9es',
    ],
    tags: ['Skill Claude .md', 'Template DOCX', 'Guide 8p', 'Valeur : 1\u202f600\u202f\u20ac'],
    file: '/resources/proposal-writer-pro.zip',
  },
  {
    id: 'process-documenter',
    category: 'RH & Ops',
    type: 'GUIDE',
    badge: 'IMPL\u00c9MENTATION',
    badgeColor: 'bg-lime-600',
    title: "Guide : Documenter tes process avec l\u2019IA en 1 jour",
    desc: "Le guide complet pour capturer et documenter tous tes processus internes en une journ\u00e9e avec l\u2019IA.",
    bullets: [
      'M\u00e9thode pas-\u00e0-pas pour cartographier tes process',
      "Templates SOP pr\u00eats \u00e0 remplir avec l\u2019IA",
      'Prompts pour transformer des notes en process',
      'Structure de knowledge base interne',
      'Guide de formation \u00e9quipe sur les nouveaux process',
    ],
    tags: ['PDF 18p', 'Templates inclus', 'Valeur : 1\u202f200\u202f\u20ac'],
    file: '/resources/process-documenter.zip',
  },
  {
    id: 'market-intel-agent',
    category: 'Direction',
    type: 'SKILL',
    badge: 'VEILLE',
    badgeColor: 'bg-violet-500',
    title: "L\u2019agent de veille concurrentielle IA",
    desc: 'Un skill qui surveille ton march\u00e9, analyse tes concurrents et te livre chaque semaine ce qui compte.',
    bullets: [
      'Analyse concurrentielle par secteur',
      'Identification des opportunit\u00e9s de march\u00e9',
      'Veille sur les tendances IA de ton industrie',
      'Benchmarking positioning et pricing',
      'Rapport hebdo de veille automatis\u00e9',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 2\u202f400\u202f\u20ac'],
    file: '/resources/market-intel-agent.zip',
  },
]
