export type ResourceCategory = 'Marketing' | 'Commercial' | 'RH & Ops' | 'Direction' | 'Copywriting' | 'SEO'
export type ResourceType = 'SKILL' | 'PROMPT' | 'GUIDE'

export interface Resource {
  id: string
  category: ResourceCategory
  type: ResourceType
  badge: string
  badgeColor: string
  title: string
  desc: string
  bullets: string[]
  tags: string[]
  file: string
}

export const CATEGORIES: ResourceCategory[] = [
  'Marketing',
  'Commercial',
  'RH & Ops',
  'Direction',
  'Copywriting',
  'SEO',
]

export const resources: Resource[] = [
  {
    id: 'marketing-ai-team',
    category: 'Marketing',
    type: 'SKILL',
    badge: 'LE PLUS TÉLÉCHARGÉ',
    badgeColor: 'bg-amber-500',
    title: "L'équipe IA qui 10x ton marketing",
    desc: "5 agents spécialisés qui automatisent ta stratégie marketing de A à Z. Ce qu'une agence facture 2 000 €/mois.",
    bullets: [
      'Agent Copywriter — tous tes textes sur mesure',
      'Agent Stratège — plan contenu 90 jours',
      'Agent SEO — optimisation automatique',
      'Agent Email — séquences de prospection',
      'Agent Analyste — analyse et recommandations',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 12p', 'Valeur : 1 800 €'],
    file: '/resources/marketing-ai-team.zip',
  },
  {
    id: 'sales-ai-team',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'LE PLUS RENTABLE',
    badgeColor: 'bg-emerald-500',
    title: "L'équipe IA qui close à ta place",
    desc: '5 agents pour tout ton cycle de vente : prospection, devis, objections, relances, onboarding client.',
    bullets: [
      'Agent Prospecteur — messages ultra-personnalisés',
      'Agent Devis — propositions qui convertissent',
      'Agent Objections — les bons arguments, toujours',
      'Agent Relance — suivi sans être relou',
      'Agent Onboarding — accueil et fidélisation client',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 2 200 €'],
    file: '/resources/sales-ai-team.zip',
  },
  {
    id: 'ops-rh-ai-team',
    category: 'RH & Ops',
    type: 'SKILL',
    badge: 'LE PLUS CONCRET',
    badgeColor: 'bg-blue-500',
    title: "L'équipe IA qui pilote tes ops",
    desc: "5 agents pour le quotidien opérationnel que personne n'aime faire mais qui coûte des heures chaque semaine.",
    bullets: [
      "Agent Planning — plannings d'équipe en 2 minutes",
      'Agent CR Réunion — notes → compte-rendu pro',
      'Agent Recrutement — fiches poste + tri CVs',
      'Agent Process — documentation SOP complète',
      'Agent Reporting — synthèse comité de direction',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 14p', 'Valeur : 1 500 €'],
    file: '/resources/ops-rh-ai-team.zip',
  },
  {
    id: 'copywriter-pro',
    category: 'Copywriting',
    type: 'PROMPT',
    badge: 'EXPERT',
    badgeColor: 'bg-purple-500',
    title: "Le copywriter IA qui écrit comme les meilleurs",
    desc: "Un system prompt de copywriter expert qui applique les frameworks AIDA, PAS, Hormozi à chaque texte que tu produis.",
    bullets: [
      'Hooks qui stoppent le scroll LinkedIn',
      'Emails de prospection qui génèrent des réponses',
      'Pages de vente structurées et persuasives',
      'Adapté à ta voix et ton secteur',
    ],
    tags: ['System Prompt GPT', 'Skill Claude', 'Valeur : 800 €'],
    file: '/resources/copywriter-pro.zip',
  },
  {
    id: 'linkedin-content-machine',
    category: 'Marketing',
    type: 'SKILL',
    badge: 'VIRAL',
    badgeColor: 'bg-pink-500',
    title: 'La machine à contenus LinkedIn',
    desc: "Un skill complet pour produire 30 posts LinkedIn par mois en 2h. Structure, hooks, calendrier éditorial, tout inclus.",
    bullets: [
      'Structure validée des meilleurs posts B2B',
      "5 types de hooks qui génèrent de l'engagement",
      "Calendrier éditorial 4 semaines prêt à l'emploi",
      'Adaptation automatique à ton secteur et ICP',
      'Recyclage de contenu existant en nouveaux posts',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 8p', 'Valeur : 1 200 €'],
    file: '/resources/linkedin-content-machine.zip',
  },
  {
    id: 'seo-content-optimizer',
    category: 'SEO',
    type: 'SKILL',
    badge: 'TECHNIQUE',
    badgeColor: 'bg-cyan-500',
    title: "L'agent SEO qui optimise tout ton contenu",
    desc: "Analyse tes pages, génère des articles optimisés, construit ta stratégie de mots-clés. Résultats en semaines.",
    bullets: [
      "Audit SEO on-page de n'importe quelle URL",
      "Génération d'articles 1500+ mots optimisés",
      'Stratégie de clusters de mots-clés par secteur',
      'Optimisation des balises meta automatique',
      'Analyse de la concurrence et opportunités',
    ],
    tags: ['Skill Claude .md', 'Guide technique 16p', 'Valeur : 2 000 €'],
    file: '/resources/seo-content-optimizer.zip',
  },
  {
    id: 'cold-email-machine',
    category: 'Commercial',
    type: 'PROMPT',
    badge: 'ÉPROUVÉ',
    badgeColor: 'bg-orange-500',
    title: 'La machine à cold emails qui convertit',
    desc: "Le prompt exact pour générer des séquences de prospection personnalisées avec un taux de réponse >15%.",
    bullets: [
      'Séquence 5 emails avec timing optimal',
      'Personnalisation automatique par secteur/ICP',
      'Objets A/B testés par type de prospect',
      'Follow-ups qui ne sont pas relous',
      'Adaptable à ton offre en 5 minutes',
    ],
    tags: ['System Prompt GPT', 'Skill Claude', 'Guide 6p', 'Valeur : 900 €'],
    file: '/resources/cold-email-machine.zip',
  },
  {
    id: 'direction-ai-assistant',
    category: 'Direction',
    type: 'SKILL',
    badge: 'STRATÉGIQUE',
    badgeColor: 'bg-indigo-500',
    title: "L'assistant IA de direction générale",
    desc: "Un agent qui pense comme un DAF/DG : analyse financière, prise de décision, synthèses stratégiques.",
    bullets: [
      'Analyse et synthèse de données financières',
      'Aide à la décision avec matrice risques/opportunités',
      'Rédaction de notes de direction et board decks',
      'Suivi des KPIs et alertes automatiques',
      'Simulation de scénarios business',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 3 000 €'],
    file: '/resources/direction-ai-assistant.zip',
  },
  {
    id: 'client-success-agent',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'FIDÉLISATION',
    badgeColor: 'bg-teal-500',
    title: "L'agent IA qui garde tes clients",
    desc: "Un skill complet pour onboarder, engager et faire monter en gamme chaque client automatiquement.",
    bullets: [
      'Séquence onboarding client sur-mesure',
      "Détection des signaux d'insatisfaction",
      "Propositions d'upsell au bon moment",
      'Rapports de suivi client automatisés',
      "Scripts d'appels de bilan trimestriel",
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 8p', 'Valeur : 1 400 €'],
    file: '/resources/client-success-agent.zip',
  },
  {
    id: 'proposal-writer-pro',
    category: 'Commercial',
    type: 'SKILL',
    badge: 'CONVERSION',
    badgeColor: 'bg-rose-500',
    title: "L'agent qui rédige tes propositions commerciales",
    desc: "Génère des devis et propositions commerciales professionnels qui signent — avec calcul ROI intégré.",
    bullets: [
      'Structure de proposition qui convertit à 60%+',
      'Calcul ROI automatique selon le profil client',
      '3 niveaux de pricing (Starter/Standard/Premium)',
      'Arguments personnalisés par secteur',
      'Réponses aux objections préparées',
    ],
    tags: ['Skill Claude .md', 'Template DOCX', 'Guide 8p', 'Valeur : 1 600 €'],
    file: '/resources/proposal-writer-pro.zip',
  },
  {
    id: 'process-documenter',
    category: 'RH & Ops',
    type: 'GUIDE',
    badge: 'IMPLÉMENTATION',
    badgeColor: 'bg-lime-600',
    title: "Guide : Documenter tes process avec l'IA en 1 jour",
    desc: "Le guide complet pour capturer et documenter tous tes processus internes en une journée avec l'IA.",
    bullets: [
      'Méthode pas-à-pas pour cartographier tes process',
      "Templates SOP prêts à remplir avec l'IA",
      'Prompts pour transformer des notes en process',
      'Structure de knowledge base interne',
      'Guide de formation équipe sur les nouveaux process',
    ],
    tags: ['PDF 18p', 'Templates inclus', 'Valeur : 1 200 €'],
    file: '/resources/process-documenter.zip',
  },
  {
    id: 'market-intel-agent',
    category: 'Direction',
    type: 'SKILL',
    badge: 'VEILLE',
    badgeColor: 'bg-violet-500',
    title: "L'agent de veille concurrentielle IA",
    desc: 'Un skill qui surveille ton marché, analyse tes concurrents et te livre chaque semaine ce qui compte.',
    bullets: [
      'Analyse concurrentielle par secteur',
      'Identification des opportunités de marché',
      'Veille sur les tendances IA de ton industrie',
      'Benchmarking positioning et pricing',
      'Rapport hebdo de veille automatisé',
    ],
    tags: ['Skill Claude .md', 'GPT Custom', 'Guide 10p', 'Valeur : 2 400 €'],
    file: '/resources/market-intel-agent.zip',
  },
]
